### ISSUE TITLE
Comentarios avance1

### ISSUE THREAD

**Issue by AliciaMstt** [andyrh0402/Tareas-Curso-BioinfInvRepro#1]
OK

Solo recuerda que aunque no sean datos genómicos queremos que utilices herramientas de línea de comando para analizarlos, pueden ser paquetes de R.

**Comment by AzaleaGuerra** [comment]
Cuidado con el formato md. Recuerda revisar cómo se ve una vez que subes tu archivo a GitHub.

**Comment by andyrh0402** [comment]
OK

Ya estoy leyendo sobre como puedo hacer los análisis que necesito en R.
